locations_data = {
    "start": {"description": "Вы стоите на перекрестке. Куда вы хотите пойти?\n1) В лес\n2) В горы\n3) К деревне",
                "options": {"1": "forest", "2": "mountains", "3": "village"},
                "pucture": "pictures/crossroad.jpg"},
    "forest": {"description": "Вы находитесь в темном лесу. Что вы хотите сделать?\n1) Идти глубже в лес\n2) Вернуться на перекресток",
                "options": {"1": "deep_forest", "2": "start"},
               "pucture": "pictures/forest.jpg"},
    "deep_forest": {"description": "Вы заблудились в лесу. Что делать?\n1) Попытаться найти дорогу\n2) Вернуться откуда пришли",
                    "options": {"1": "find_path", "2": "forest"},
                    "pucture": "pictures/forest.jpg"},
    "find_path": {"description": "Поздравляю, вы нашли дорогу и выбрались из леса!",
                  "options": {},
                  "pucture": "pictures/win.jpg"},
    "mountains": {"description": "Вы поднимаетесь в горы. Что вы видите?\n1) Водопад\n2) Пещера\n3) Вернуться на перекресток",
                    "options": {"1": "waterfall", "2": "cave", "3": "start"},
                    "pucture": "pictures/mountains.jpg"},
    "waterfall": {"description": "Вы находитесь у водопада. Ваши действия?\n1) Подойти ближе\n2) Вернуться в горы",
                    "options": {"1": "approach_waterfall", "2": "mountains"},
                    "pucture": "pictures/waterfall.jpg"},
    "approach_waterfall": {"description": "Ого, это волшебный водопад! Вы получили волшебные силы и покинули горы.",
                            "options": {},
                            "pucture": "pictures/win.jpg"},
    "cave": {"description": "Вы вошли в пещеру. Что делать дальше?\n1) Исследовать глубже\n2) Выйти из пещеры",
            "options": {"1": "explore_cave", "2": "mountains"},
            "pucture": "pictures/cave.jpg"},
    "explore_cave": {"description": "Увы, вас здесь поджидал медведь. Вы проиграли!",
                    "options": {},
                    "pucture": "pictures/bear.jpg"},
    "village": {"description": "Вы пришли в деревню. Жители рады вас видеть. Что вы хотите сделать?\n1) Поговорить с жителями\n2) Покинуть деревню",
                "options": {"1": "talk_to_villagers", "2": "start"},
                "pucture": "pictures/village.jpg"},
    "talk_to_villagers": {"description": "Жители рассказали вам много интересных историй. Вы провели отличное время в деревне!",
        "options": {},
        "pucture": "pictures/villager.jpg"}
}